[package]
name = "Sailfish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "sailfish"
path = "src/server.rs"

[[bin]]
name = "sailfish-cli"
path = "src/cli.rs"
